language: java
dist: trusty
sudo: required
jdk:
  - oraclejdk8
install:
  - cd desappgroupc1hbackend && mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: d75c7509-1a26-4283-ba25-3e59df710b8f
    app: Grupo-C1H-022019