language: java
dist: trusty
sudo: required
cache: 
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
script: 
  - cd desapp-groupc1h-backend 
  - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

  after_success:
    - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
notifications:
  email:
    recipients:
      - lisar.3467@gmail.com
      - miloromiguel@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
